// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/TheThingsNetwork/api/router/router.proto

package org.thethingsnetwork.api.router;

public final class RouterProto {
  private RouterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_UplinkMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_UplinkMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_DownlinkMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_DownlinkMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_DeviceActivationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_DeviceActivationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_DeviceActivationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_DeviceActivationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_GatewayStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_GatewayStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_GatewayStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_GatewayStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_router_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_router_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3github.com/TheThingsNetwork/api/router" +
      "/router.proto\022\006router\032\033google/protobuf/e" +
      "mpty.proto\032-github.com/gogo/protobuf/gog" +
      "oproto/gogo.proto\032)github.com/TheThingsN" +
      "etwork/api/api.proto\0327github.com/TheThin" +
      "gsNetwork/api/protocol/protocol.proto\0325g" +
      "ithub.com/TheThingsNetwork/api/gateway/g" +
      "ateway.proto\0321github.com/TheThingsNetwor" +
      "k/api/trace/trace.proto\"\022\n\020SubscribeRequ" +
      "est\"\301\001\n\rUplinkMessage\022\017\n\007payload\030\001 \001(\014\022\"",
      "\n\007message\030\002 \001(\0132\021.protocol.Message\022/\n\021pr" +
      "otocol_metadata\030\013 \001(\0132\024.protocol.RxMetad" +
      "ata\022-\n\020gateway_metadata\030\014 \001(\0132\023.gateway." +
      "RxMetadata\022\033\n\005trace\030\025 \001(\0132\014.trace.Trace\"" +
      "\327\001\n\017DownlinkMessage\022\017\n\007payload\030\001 \001(\014\022\"\n\007" +
      "message\030\002 \001(\0132\021.protocol.Message\0229\n\026prot" +
      "ocol_configuration\030\013 \001(\0132\031.protocol.TxCo" +
      "nfiguration\0227\n\025gateway_configuration\030\014 \001" +
      "(\0132\030.gateway.TxConfiguration\022\033\n\005trace\030\025 " +
      "\001(\0132\014.trace.Trace\"\252\003\n\027DeviceActivationRe",
      "quest\022\017\n\007payload\030\001 \001(\014\022\"\n\007message\030\002 \001(\0132" +
      "\021.protocol.Message\022P\n\007dev_eui\030\013 \001(\014B?\342\336\037" +
      "\006DevEUI\332\336\0371github.com/TheThingsNetwork/t" +
      "tn/core/types.DevEUI\022P\n\007app_eui\030\014 \001(\014B?\342" +
      "\336\037\006AppEUI\332\336\0371github.com/TheThingsNetwork" +
      "/ttn/core/types.AppEUI\022/\n\021protocol_metad" +
      "ata\030\025 \001(\0132\024.protocol.RxMetadata\022-\n\020gatew" +
      "ay_metadata\030\026 \001(\0132\023.gateway.RxMetadata\0229" +
      "\n\023activation_metadata\030\027 \001(\0132\034.protocol.A" +
      "ctivationMetadata\022\033\n\005trace\030\037 \001(\0132\014.trace",
      ".Trace\"\032\n\030DeviceActivationResponse\"9\n\024Ga" +
      "tewayStatusRequest\022!\n\ngateway_id\030\001 \001(\tB\r" +
      "\342\336\037\tGatewayID\"K\n\025GatewayStatusResponse\022\021" +
      "\n\tlast_seen\030\001 \001(\003\022\037\n\006status\030\002 \001(\0132\017.gate" +
      "way.Status\"\017\n\rStatusRequest\"\210\002\n\006Status\022 " +
      "\n\006system\030\001 \001(\0132\020.api.SystemStats\022&\n\tcomp" +
      "onent\030\002 \001(\0132\023.api.ComponentStats\022\"\n\016gate" +
      "way_status\030\013 \001(\0132\n.api.Rates\022\032\n\006uplink\030\014" +
      " \001(\0132\n.api.Rates\022\034\n\010downlink\030\r \001(\0132\n.api" +
      ".Rates\022\037\n\013activations\030\016 \001(\0132\n.api.Rates\022",
      "\032\n\022connected_gateways\030\025 \001(\r\022\031\n\021connected" +
      "_brokers\030\026 \001(\r2\220\002\n\006Router\022:\n\rGatewayStat" +
      "us\022\017.gateway.Status\032\026.google.protobuf.Em" +
      "pty(\001\0229\n\006Uplink\022\025.router.UplinkMessage\032\026" +
      ".google.protobuf.Empty(\001\022@\n\tSubscribe\022\030." +
      "router.SubscribeRequest\032\027.router.Downlin" +
      "kMessage0\001\022M\n\010Activate\022\037.router.DeviceAc" +
      "tivationRequest\032 .router.DeviceActivatio" +
      "nResponse2\221\001\n\rRouterManager\022L\n\rGatewaySt" +
      "atus\022\034.router.GatewayStatusRequest\032\035.rou",
      "ter.GatewayStatusResponse\0222\n\tGetStatus\022\025" +
      ".router.StatusRequest\032\016.router.StatusBv\n" +
      "\037org.thethingsnetwork.api.routerB\013Router" +
      "ProtoP\001Z&github.com/TheThingsNetwork/api" +
      "/router\252\002\033TheThingsNetwork.API.Routerb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
          org.thethingsnetwork.api.APIProto.getDescriptor(),
          org.thethingsnetwork.api.protocol.ProtocolProto.getDescriptor(),
          org.thethingsnetwork.api.gateway.GatewayProto.getDescriptor(),
          org.thethingsnetwork.api.trace.TraceProto.getDescriptor(),
        }, assigner);
    internal_static_router_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_router_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_SubscribeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_router_UplinkMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_router_UplinkMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_UplinkMessage_descriptor,
        new java.lang.String[] { "Payload", "Message", "ProtocolMetadata", "GatewayMetadata", "Trace", });
    internal_static_router_DownlinkMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_router_DownlinkMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_DownlinkMessage_descriptor,
        new java.lang.String[] { "Payload", "Message", "ProtocolConfiguration", "GatewayConfiguration", "Trace", });
    internal_static_router_DeviceActivationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_router_DeviceActivationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_DeviceActivationRequest_descriptor,
        new java.lang.String[] { "Payload", "Message", "DevEui", "AppEui", "ProtocolMetadata", "GatewayMetadata", "ActivationMetadata", "Trace", });
    internal_static_router_DeviceActivationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_router_DeviceActivationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_DeviceActivationResponse_descriptor,
        new java.lang.String[] { });
    internal_static_router_GatewayStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_router_GatewayStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_GatewayStatusRequest_descriptor,
        new java.lang.String[] { "GatewayId", });
    internal_static_router_GatewayStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_router_GatewayStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_GatewayStatusResponse_descriptor,
        new java.lang.String[] { "LastSeen", "Status", });
    internal_static_router_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_router_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_StatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_router_Status_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_router_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_router_Status_descriptor,
        new java.lang.String[] { "System", "Component", "GatewayStatus", "Uplink", "Downlink", "Activations", "ConnectedGateways", "ConnectedBrokers", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.customname);
    registry.add(com.google.protobuf.GoGoProtos.customtype);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
    org.thethingsnetwork.api.APIProto.getDescriptor();
    org.thethingsnetwork.api.protocol.ProtocolProto.getDescriptor();
    org.thethingsnetwork.api.gateway.GatewayProto.getDescriptor();
    org.thethingsnetwork.api.trace.TraceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
