<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/TheThingsNetwork/api/trace/trace.proto

namespace GPBMetadata\GithubCom\TheThingsNetwork\Api\Trace;

class Trace
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\GithubCom\Gogo\Protobuf\Gogoproto\Gogo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8030a316769746875622e636f6d2f5468655468696e67734e6574776f" .
            "726b2f6170692f74726163652f74726163652e70726f746f120574726163" .
            "6522ef010a05547261636512120a0269641801200128094206e2de1f0249" .
            "44120c0a0474696d6518022001280312210a0a736572766963655f696418" .
            "0320012809420de2de1f0953657276696365494412140a0c736572766963" .
            "655f6e616d65180420012809120d0a056576656e74180520012809122c0a" .
            "086d6574616461746118062003280b321a2e74726163652e54726163652e" .
            "4d65746164617461456e747279121d0a07706172656e7473180b2003280b" .
            "320c2e74726163652e54726163651a2f0a0d4d65746164617461456e7472" .
            "79120b0a036b6579180120012809120d0a0576616c75651802200128093a" .
            "02380142720a1e6f72672e7468657468696e67736e6574776f726b2e6170" .
            "692e7472616365420a547261636550726f746f50015a256769746875622e" .
            "636f6d2f5468655468696e67734e6574776f726b2f6170692f7472616365" .
            "aa021a5468655468696e67734e6574776f726b2e4150492e547261636562" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

