<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/TheThingsNetwork/api/router/router.proto

namespace Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * message StatusRequest is used to request the status of this Router
 *
 * Generated from protobuf message <code>router.StatusRequest</code>
 */
class StatusRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\GithubCom\TheThingsNetwork\Api\Router\Router::initOnce();
        parent::__construct();
    }

}

