// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/TheThingsNetwork/api/broker/broker.proto

package org.thethingsnetwork.api.broker;

public interface DownlinkOptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.DownlinkOption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * String that identifies this downlink option in the Router
   * </pre>
   *
   * <code>string identifier = 1;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <pre>
   * String that identifies this downlink option in the Router
   * </pre>
   *
   * <code>string identifier = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  /**
   * <pre>
   * ID of the gateway where this downlink should be sent
   * </pre>
   *
   * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
   */
  java.lang.String getGatewayId();
  /**
   * <pre>
   * ID of the gateway where this downlink should be sent
   * </pre>
   *
   * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
   */
  com.google.protobuf.ByteString
      getGatewayIdBytes();

  /**
   * <pre>
   * Score of this downlink option. Lower is better.
   * </pre>
   *
   * <code>uint32 score = 3;</code>
   */
  int getScore();

  /**
   * <pre>
   * deadline time at server represented as Unix nanoseconds
   * </pre>
   *
   * <code>int64 deadline = 4;</code>
   */
  long getDeadline();

  /**
   * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
   */
  boolean hasProtocolConfiguration();
  /**
   * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.protocol.TxConfiguration getProtocolConfiguration();
  /**
   * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.protocol.TxConfigurationOrBuilder getProtocolConfigurationOrBuilder();

  /**
   * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
   */
  boolean hasGatewayConfiguration();
  /**
   * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.gateway.TxConfiguration getGatewayConfiguration();
  /**
   * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.gateway.TxConfigurationOrBuilder getGatewayConfigurationOrBuilder();
}
