// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/TheThingsNetwork/api/broker/broker.proto

package org.thethingsnetwork.api.broker;

/**
 * Protobuf type {@code broker.DownlinkOption}
 */
public  final class DownlinkOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:broker.DownlinkOption)
    DownlinkOptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DownlinkOption.newBuilder() to construct.
  private DownlinkOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DownlinkOption() {
    identifier_ = "";
    gatewayId_ = "";
    score_ = 0;
    deadline_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DownlinkOption(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            identifier_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            gatewayId_ = s;
            break;
          }
          case 24: {

            score_ = input.readUInt32();
            break;
          }
          case 32: {

            deadline_ = input.readInt64();
            break;
          }
          case 42: {
            org.thethingsnetwork.api.protocol.TxConfiguration.Builder subBuilder = null;
            if (protocolConfiguration_ != null) {
              subBuilder = protocolConfiguration_.toBuilder();
            }
            protocolConfiguration_ = input.readMessage(org.thethingsnetwork.api.protocol.TxConfiguration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(protocolConfiguration_);
              protocolConfiguration_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            org.thethingsnetwork.api.gateway.TxConfiguration.Builder subBuilder = null;
            if (gatewayConfiguration_ != null) {
              subBuilder = gatewayConfiguration_.toBuilder();
            }
            gatewayConfiguration_ = input.readMessage(org.thethingsnetwork.api.gateway.TxConfiguration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(gatewayConfiguration_);
              gatewayConfiguration_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.thethingsnetwork.api.broker.BrokerProto.internal_static_broker_DownlinkOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.thethingsnetwork.api.broker.BrokerProto.internal_static_broker_DownlinkOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.thethingsnetwork.api.broker.DownlinkOption.class, org.thethingsnetwork.api.broker.DownlinkOption.Builder.class);
  }

  public static final int IDENTIFIER_FIELD_NUMBER = 1;
  private volatile java.lang.Object identifier_;
  /**
   * <pre>
   * String that identifies this downlink option in the Router
   * </pre>
   *
   * <code>string identifier = 1;</code>
   */
  public java.lang.String getIdentifier() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      identifier_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * String that identifies this downlink option in the Router
   * </pre>
   *
   * <code>string identifier = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdentifierBytes() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      identifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GATEWAY_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object gatewayId_;
  /**
   * <pre>
   * ID of the gateway where this downlink should be sent
   * </pre>
   *
   * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
   */
  public java.lang.String getGatewayId() {
    java.lang.Object ref = gatewayId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gatewayId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID of the gateway where this downlink should be sent
   * </pre>
   *
   * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
   */
  public com.google.protobuf.ByteString
      getGatewayIdBytes() {
    java.lang.Object ref = gatewayId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gatewayId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORE_FIELD_NUMBER = 3;
  private int score_;
  /**
   * <pre>
   * Score of this downlink option. Lower is better.
   * </pre>
   *
   * <code>uint32 score = 3;</code>
   */
  public int getScore() {
    return score_;
  }

  public static final int DEADLINE_FIELD_NUMBER = 4;
  private long deadline_;
  /**
   * <pre>
   * deadline time at server represented as Unix nanoseconds
   * </pre>
   *
   * <code>int64 deadline = 4;</code>
   */
  public long getDeadline() {
    return deadline_;
  }

  public static final int PROTOCOL_CONFIGURATION_FIELD_NUMBER = 5;
  private org.thethingsnetwork.api.protocol.TxConfiguration protocolConfiguration_;
  /**
   * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
   */
  public boolean hasProtocolConfiguration() {
    return protocolConfiguration_ != null;
  }
  /**
   * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
   */
  public org.thethingsnetwork.api.protocol.TxConfiguration getProtocolConfiguration() {
    return protocolConfiguration_ == null ? org.thethingsnetwork.api.protocol.TxConfiguration.getDefaultInstance() : protocolConfiguration_;
  }
  /**
   * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
   */
  public org.thethingsnetwork.api.protocol.TxConfigurationOrBuilder getProtocolConfigurationOrBuilder() {
    return getProtocolConfiguration();
  }

  public static final int GATEWAY_CONFIGURATION_FIELD_NUMBER = 6;
  private org.thethingsnetwork.api.gateway.TxConfiguration gatewayConfiguration_;
  /**
   * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
   */
  public boolean hasGatewayConfiguration() {
    return gatewayConfiguration_ != null;
  }
  /**
   * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
   */
  public org.thethingsnetwork.api.gateway.TxConfiguration getGatewayConfiguration() {
    return gatewayConfiguration_ == null ? org.thethingsnetwork.api.gateway.TxConfiguration.getDefaultInstance() : gatewayConfiguration_;
  }
  /**
   * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
   */
  public org.thethingsnetwork.api.gateway.TxConfigurationOrBuilder getGatewayConfigurationOrBuilder() {
    return getGatewayConfiguration();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdentifierBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, identifier_);
    }
    if (!getGatewayIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gatewayId_);
    }
    if (score_ != 0) {
      output.writeUInt32(3, score_);
    }
    if (deadline_ != 0L) {
      output.writeInt64(4, deadline_);
    }
    if (protocolConfiguration_ != null) {
      output.writeMessage(5, getProtocolConfiguration());
    }
    if (gatewayConfiguration_ != null) {
      output.writeMessage(6, getGatewayConfiguration());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdentifierBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, identifier_);
    }
    if (!getGatewayIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gatewayId_);
    }
    if (score_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, score_);
    }
    if (deadline_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, deadline_);
    }
    if (protocolConfiguration_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getProtocolConfiguration());
    }
    if (gatewayConfiguration_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getGatewayConfiguration());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.thethingsnetwork.api.broker.DownlinkOption)) {
      return super.equals(obj);
    }
    org.thethingsnetwork.api.broker.DownlinkOption other = (org.thethingsnetwork.api.broker.DownlinkOption) obj;

    boolean result = true;
    result = result && getIdentifier()
        .equals(other.getIdentifier());
    result = result && getGatewayId()
        .equals(other.getGatewayId());
    result = result && (getScore()
        == other.getScore());
    result = result && (getDeadline()
        == other.getDeadline());
    result = result && (hasProtocolConfiguration() == other.hasProtocolConfiguration());
    if (hasProtocolConfiguration()) {
      result = result && getProtocolConfiguration()
          .equals(other.getProtocolConfiguration());
    }
    result = result && (hasGatewayConfiguration() == other.hasGatewayConfiguration());
    if (hasGatewayConfiguration()) {
      result = result && getGatewayConfiguration()
          .equals(other.getGatewayConfiguration());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
    hash = (53 * hash) + getIdentifier().hashCode();
    hash = (37 * hash) + GATEWAY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGatewayId().hashCode();
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getScore();
    hash = (37 * hash) + DEADLINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeadline());
    if (hasProtocolConfiguration()) {
      hash = (37 * hash) + PROTOCOL_CONFIGURATION_FIELD_NUMBER;
      hash = (53 * hash) + getProtocolConfiguration().hashCode();
    }
    if (hasGatewayConfiguration()) {
      hash = (37 * hash) + GATEWAY_CONFIGURATION_FIELD_NUMBER;
      hash = (53 * hash) + getGatewayConfiguration().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.thethingsnetwork.api.broker.DownlinkOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.thethingsnetwork.api.broker.DownlinkOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code broker.DownlinkOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:broker.DownlinkOption)
      org.thethingsnetwork.api.broker.DownlinkOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.thethingsnetwork.api.broker.BrokerProto.internal_static_broker_DownlinkOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.thethingsnetwork.api.broker.BrokerProto.internal_static_broker_DownlinkOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.thethingsnetwork.api.broker.DownlinkOption.class, org.thethingsnetwork.api.broker.DownlinkOption.Builder.class);
    }

    // Construct using org.thethingsnetwork.api.broker.DownlinkOption.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      identifier_ = "";

      gatewayId_ = "";

      score_ = 0;

      deadline_ = 0L;

      if (protocolConfigurationBuilder_ == null) {
        protocolConfiguration_ = null;
      } else {
        protocolConfiguration_ = null;
        protocolConfigurationBuilder_ = null;
      }
      if (gatewayConfigurationBuilder_ == null) {
        gatewayConfiguration_ = null;
      } else {
        gatewayConfiguration_ = null;
        gatewayConfigurationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.thethingsnetwork.api.broker.BrokerProto.internal_static_broker_DownlinkOption_descriptor;
    }

    @java.lang.Override
    public org.thethingsnetwork.api.broker.DownlinkOption getDefaultInstanceForType() {
      return org.thethingsnetwork.api.broker.DownlinkOption.getDefaultInstance();
    }

    @java.lang.Override
    public org.thethingsnetwork.api.broker.DownlinkOption build() {
      org.thethingsnetwork.api.broker.DownlinkOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.thethingsnetwork.api.broker.DownlinkOption buildPartial() {
      org.thethingsnetwork.api.broker.DownlinkOption result = new org.thethingsnetwork.api.broker.DownlinkOption(this);
      result.identifier_ = identifier_;
      result.gatewayId_ = gatewayId_;
      result.score_ = score_;
      result.deadline_ = deadline_;
      if (protocolConfigurationBuilder_ == null) {
        result.protocolConfiguration_ = protocolConfiguration_;
      } else {
        result.protocolConfiguration_ = protocolConfigurationBuilder_.build();
      }
      if (gatewayConfigurationBuilder_ == null) {
        result.gatewayConfiguration_ = gatewayConfiguration_;
      } else {
        result.gatewayConfiguration_ = gatewayConfigurationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.thethingsnetwork.api.broker.DownlinkOption) {
        return mergeFrom((org.thethingsnetwork.api.broker.DownlinkOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.thethingsnetwork.api.broker.DownlinkOption other) {
      if (other == org.thethingsnetwork.api.broker.DownlinkOption.getDefaultInstance()) return this;
      if (!other.getIdentifier().isEmpty()) {
        identifier_ = other.identifier_;
        onChanged();
      }
      if (!other.getGatewayId().isEmpty()) {
        gatewayId_ = other.gatewayId_;
        onChanged();
      }
      if (other.getScore() != 0) {
        setScore(other.getScore());
      }
      if (other.getDeadline() != 0L) {
        setDeadline(other.getDeadline());
      }
      if (other.hasProtocolConfiguration()) {
        mergeProtocolConfiguration(other.getProtocolConfiguration());
      }
      if (other.hasGatewayConfiguration()) {
        mergeGatewayConfiguration(other.getGatewayConfiguration());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.thethingsnetwork.api.broker.DownlinkOption parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.thethingsnetwork.api.broker.DownlinkOption) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object identifier_ = "";
    /**
     * <pre>
     * String that identifies this downlink option in the Router
     * </pre>
     *
     * <code>string identifier = 1;</code>
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * String that identifies this downlink option in the Router
     * </pre>
     *
     * <code>string identifier = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * String that identifies this downlink option in the Router
     * </pre>
     *
     * <code>string identifier = 1;</code>
     */
    public Builder setIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      identifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * String that identifies this downlink option in the Router
     * </pre>
     *
     * <code>string identifier = 1;</code>
     */
    public Builder clearIdentifier() {
      
      identifier_ = getDefaultInstance().getIdentifier();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * String that identifies this downlink option in the Router
     * </pre>
     *
     * <code>string identifier = 1;</code>
     */
    public Builder setIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      identifier_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object gatewayId_ = "";
    /**
     * <pre>
     * ID of the gateway where this downlink should be sent
     * </pre>
     *
     * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
     */
    public java.lang.String getGatewayId() {
      java.lang.Object ref = gatewayId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gatewayId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID of the gateway where this downlink should be sent
     * </pre>
     *
     * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
     */
    public com.google.protobuf.ByteString
        getGatewayIdBytes() {
      java.lang.Object ref = gatewayId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gatewayId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID of the gateway where this downlink should be sent
     * </pre>
     *
     * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
     */
    public Builder setGatewayId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gatewayId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the gateway where this downlink should be sent
     * </pre>
     *
     * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
     */
    public Builder clearGatewayId() {
      
      gatewayId_ = getDefaultInstance().getGatewayId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the gateway where this downlink should be sent
     * </pre>
     *
     * <code>string gateway_id = 2 [(.gogoproto.customname) = "GatewayID"];</code>
     */
    public Builder setGatewayIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gatewayId_ = value;
      onChanged();
      return this;
    }

    private int score_ ;
    /**
     * <pre>
     * Score of this downlink option. Lower is better.
     * </pre>
     *
     * <code>uint32 score = 3;</code>
     */
    public int getScore() {
      return score_;
    }
    /**
     * <pre>
     * Score of this downlink option. Lower is better.
     * </pre>
     *
     * <code>uint32 score = 3;</code>
     */
    public Builder setScore(int value) {
      
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Score of this downlink option. Lower is better.
     * </pre>
     *
     * <code>uint32 score = 3;</code>
     */
    public Builder clearScore() {
      
      score_ = 0;
      onChanged();
      return this;
    }

    private long deadline_ ;
    /**
     * <pre>
     * deadline time at server represented as Unix nanoseconds
     * </pre>
     *
     * <code>int64 deadline = 4;</code>
     */
    public long getDeadline() {
      return deadline_;
    }
    /**
     * <pre>
     * deadline time at server represented as Unix nanoseconds
     * </pre>
     *
     * <code>int64 deadline = 4;</code>
     */
    public Builder setDeadline(long value) {
      
      deadline_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * deadline time at server represented as Unix nanoseconds
     * </pre>
     *
     * <code>int64 deadline = 4;</code>
     */
    public Builder clearDeadline() {
      
      deadline_ = 0L;
      onChanged();
      return this;
    }

    private org.thethingsnetwork.api.protocol.TxConfiguration protocolConfiguration_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.thethingsnetwork.api.protocol.TxConfiguration, org.thethingsnetwork.api.protocol.TxConfiguration.Builder, org.thethingsnetwork.api.protocol.TxConfigurationOrBuilder> protocolConfigurationBuilder_;
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    public boolean hasProtocolConfiguration() {
      return protocolConfigurationBuilder_ != null || protocolConfiguration_ != null;
    }
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    public org.thethingsnetwork.api.protocol.TxConfiguration getProtocolConfiguration() {
      if (protocolConfigurationBuilder_ == null) {
        return protocolConfiguration_ == null ? org.thethingsnetwork.api.protocol.TxConfiguration.getDefaultInstance() : protocolConfiguration_;
      } else {
        return protocolConfigurationBuilder_.getMessage();
      }
    }
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setProtocolConfiguration(org.thethingsnetwork.api.protocol.TxConfiguration value) {
      if (protocolConfigurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        protocolConfiguration_ = value;
        onChanged();
      } else {
        protocolConfigurationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setProtocolConfiguration(
        org.thethingsnetwork.api.protocol.TxConfiguration.Builder builderForValue) {
      if (protocolConfigurationBuilder_ == null) {
        protocolConfiguration_ = builderForValue.build();
        onChanged();
      } else {
        protocolConfigurationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    public Builder mergeProtocolConfiguration(org.thethingsnetwork.api.protocol.TxConfiguration value) {
      if (protocolConfigurationBuilder_ == null) {
        if (protocolConfiguration_ != null) {
          protocolConfiguration_ =
            org.thethingsnetwork.api.protocol.TxConfiguration.newBuilder(protocolConfiguration_).mergeFrom(value).buildPartial();
        } else {
          protocolConfiguration_ = value;
        }
        onChanged();
      } else {
        protocolConfigurationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    public Builder clearProtocolConfiguration() {
      if (protocolConfigurationBuilder_ == null) {
        protocolConfiguration_ = null;
        onChanged();
      } else {
        protocolConfiguration_ = null;
        protocolConfigurationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    public org.thethingsnetwork.api.protocol.TxConfiguration.Builder getProtocolConfigurationBuilder() {
      
      onChanged();
      return getProtocolConfigurationFieldBuilder().getBuilder();
    }
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    public org.thethingsnetwork.api.protocol.TxConfigurationOrBuilder getProtocolConfigurationOrBuilder() {
      if (protocolConfigurationBuilder_ != null) {
        return protocolConfigurationBuilder_.getMessageOrBuilder();
      } else {
        return protocolConfiguration_ == null ?
            org.thethingsnetwork.api.protocol.TxConfiguration.getDefaultInstance() : protocolConfiguration_;
      }
    }
    /**
     * <code>.protocol.TxConfiguration protocol_configuration = 5 [(.gogoproto.nullable) = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.thethingsnetwork.api.protocol.TxConfiguration, org.thethingsnetwork.api.protocol.TxConfiguration.Builder, org.thethingsnetwork.api.protocol.TxConfigurationOrBuilder> 
        getProtocolConfigurationFieldBuilder() {
      if (protocolConfigurationBuilder_ == null) {
        protocolConfigurationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.thethingsnetwork.api.protocol.TxConfiguration, org.thethingsnetwork.api.protocol.TxConfiguration.Builder, org.thethingsnetwork.api.protocol.TxConfigurationOrBuilder>(
                getProtocolConfiguration(),
                getParentForChildren(),
                isClean());
        protocolConfiguration_ = null;
      }
      return protocolConfigurationBuilder_;
    }

    private org.thethingsnetwork.api.gateway.TxConfiguration gatewayConfiguration_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.thethingsnetwork.api.gateway.TxConfiguration, org.thethingsnetwork.api.gateway.TxConfiguration.Builder, org.thethingsnetwork.api.gateway.TxConfigurationOrBuilder> gatewayConfigurationBuilder_;
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    public boolean hasGatewayConfiguration() {
      return gatewayConfigurationBuilder_ != null || gatewayConfiguration_ != null;
    }
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    public org.thethingsnetwork.api.gateway.TxConfiguration getGatewayConfiguration() {
      if (gatewayConfigurationBuilder_ == null) {
        return gatewayConfiguration_ == null ? org.thethingsnetwork.api.gateway.TxConfiguration.getDefaultInstance() : gatewayConfiguration_;
      } else {
        return gatewayConfigurationBuilder_.getMessage();
      }
    }
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setGatewayConfiguration(org.thethingsnetwork.api.gateway.TxConfiguration value) {
      if (gatewayConfigurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gatewayConfiguration_ = value;
        onChanged();
      } else {
        gatewayConfigurationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    public Builder setGatewayConfiguration(
        org.thethingsnetwork.api.gateway.TxConfiguration.Builder builderForValue) {
      if (gatewayConfigurationBuilder_ == null) {
        gatewayConfiguration_ = builderForValue.build();
        onChanged();
      } else {
        gatewayConfigurationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    public Builder mergeGatewayConfiguration(org.thethingsnetwork.api.gateway.TxConfiguration value) {
      if (gatewayConfigurationBuilder_ == null) {
        if (gatewayConfiguration_ != null) {
          gatewayConfiguration_ =
            org.thethingsnetwork.api.gateway.TxConfiguration.newBuilder(gatewayConfiguration_).mergeFrom(value).buildPartial();
        } else {
          gatewayConfiguration_ = value;
        }
        onChanged();
      } else {
        gatewayConfigurationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    public Builder clearGatewayConfiguration() {
      if (gatewayConfigurationBuilder_ == null) {
        gatewayConfiguration_ = null;
        onChanged();
      } else {
        gatewayConfiguration_ = null;
        gatewayConfigurationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    public org.thethingsnetwork.api.gateway.TxConfiguration.Builder getGatewayConfigurationBuilder() {
      
      onChanged();
      return getGatewayConfigurationFieldBuilder().getBuilder();
    }
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    public org.thethingsnetwork.api.gateway.TxConfigurationOrBuilder getGatewayConfigurationOrBuilder() {
      if (gatewayConfigurationBuilder_ != null) {
        return gatewayConfigurationBuilder_.getMessageOrBuilder();
      } else {
        return gatewayConfiguration_ == null ?
            org.thethingsnetwork.api.gateway.TxConfiguration.getDefaultInstance() : gatewayConfiguration_;
      }
    }
    /**
     * <code>.gateway.TxConfiguration gateway_configuration = 6 [(.gogoproto.nullable) = false];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.thethingsnetwork.api.gateway.TxConfiguration, org.thethingsnetwork.api.gateway.TxConfiguration.Builder, org.thethingsnetwork.api.gateway.TxConfigurationOrBuilder> 
        getGatewayConfigurationFieldBuilder() {
      if (gatewayConfigurationBuilder_ == null) {
        gatewayConfigurationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.thethingsnetwork.api.gateway.TxConfiguration, org.thethingsnetwork.api.gateway.TxConfiguration.Builder, org.thethingsnetwork.api.gateway.TxConfigurationOrBuilder>(
                getGatewayConfiguration(),
                getParentForChildren(),
                isClean());
        gatewayConfiguration_ = null;
      }
      return gatewayConfigurationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:broker.DownlinkOption)
  }

  // @@protoc_insertion_point(class_scope:broker.DownlinkOption)
  private static final org.thethingsnetwork.api.broker.DownlinkOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.thethingsnetwork.api.broker.DownlinkOption();
  }

  public static org.thethingsnetwork.api.broker.DownlinkOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DownlinkOption>
      PARSER = new com.google.protobuf.AbstractParser<DownlinkOption>() {
    @java.lang.Override
    public DownlinkOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DownlinkOption(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DownlinkOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DownlinkOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.thethingsnetwork.api.broker.DownlinkOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

