// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/TheThingsNetwork/api/broker/broker.proto

package org.thethingsnetwork.api.broker;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:broker.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api.SystemStats system = 1 [(.gogoproto.nullable) = false];</code>
   */
  boolean hasSystem();
  /**
   * <code>.api.SystemStats system = 1 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.SystemStats getSystem();
  /**
   * <code>.api.SystemStats system = 1 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.SystemStatsOrBuilder getSystemOrBuilder();

  /**
   * <code>.api.ComponentStats component = 2 [(.gogoproto.nullable) = false];</code>
   */
  boolean hasComponent();
  /**
   * <code>.api.ComponentStats component = 2 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.ComponentStats getComponent();
  /**
   * <code>.api.ComponentStats component = 2 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.ComponentStatsOrBuilder getComponentOrBuilder();

  /**
   * <code>.api.Rates uplink = 11;</code>
   */
  boolean hasUplink();
  /**
   * <code>.api.Rates uplink = 11;</code>
   */
  org.thethingsnetwork.api.Rates getUplink();
  /**
   * <code>.api.Rates uplink = 11;</code>
   */
  org.thethingsnetwork.api.RatesOrBuilder getUplinkOrBuilder();

  /**
   * <code>.api.Rates uplink_unique = 12;</code>
   */
  boolean hasUplinkUnique();
  /**
   * <code>.api.Rates uplink_unique = 12;</code>
   */
  org.thethingsnetwork.api.Rates getUplinkUnique();
  /**
   * <code>.api.Rates uplink_unique = 12;</code>
   */
  org.thethingsnetwork.api.RatesOrBuilder getUplinkUniqueOrBuilder();

  /**
   * <code>.api.Rates downlink = 13;</code>
   */
  boolean hasDownlink();
  /**
   * <code>.api.Rates downlink = 13;</code>
   */
  org.thethingsnetwork.api.Rates getDownlink();
  /**
   * <code>.api.Rates downlink = 13;</code>
   */
  org.thethingsnetwork.api.RatesOrBuilder getDownlinkOrBuilder();

  /**
   * <code>.api.Rates activations = 14;</code>
   */
  boolean hasActivations();
  /**
   * <code>.api.Rates activations = 14;</code>
   */
  org.thethingsnetwork.api.Rates getActivations();
  /**
   * <code>.api.Rates activations = 14;</code>
   */
  org.thethingsnetwork.api.RatesOrBuilder getActivationsOrBuilder();

  /**
   * <code>.api.Rates activations_unique = 15;</code>
   */
  boolean hasActivationsUnique();
  /**
   * <code>.api.Rates activations_unique = 15;</code>
   */
  org.thethingsnetwork.api.Rates getActivationsUnique();
  /**
   * <code>.api.Rates activations_unique = 15;</code>
   */
  org.thethingsnetwork.api.RatesOrBuilder getActivationsUniqueOrBuilder();

  /**
   * <code>.api.Percentiles deduplication = 16;</code>
   */
  boolean hasDeduplication();
  /**
   * <code>.api.Percentiles deduplication = 16;</code>
   */
  org.thethingsnetwork.api.Percentiles getDeduplication();
  /**
   * <code>.api.Percentiles deduplication = 16;</code>
   */
  org.thethingsnetwork.api.PercentilesOrBuilder getDeduplicationOrBuilder();

  /**
   * <pre>
   * Connections
   * </pre>
   *
   * <code>uint32 connected_routers = 21;</code>
   */
  int getConnectedRouters();

  /**
   * <code>uint32 connected_handlers = 22;</code>
   */
  int getConnectedHandlers();
}
