<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/TheThingsNetwork/api/handler/handler.proto

namespace Handler;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * DryUplinkResult is the result from an uplink simulation
 *
 * Generated from protobuf message <code>handler.DryUplinkResult</code>
 */
class DryUplinkResult extends \Google\Protobuf\Internal\Message
{
    /**
     * The binary payload
     *
     * Generated from protobuf field <code>bytes payload = 1;</code>
     */
    private $payload = '';
    /**
     * The decoded fields
     *
     * Generated from protobuf field <code>string fields = 2;</code>
     */
    private $fields = '';
    /**
     * Was validation of the message successful
     *
     * Generated from protobuf field <code>bool valid = 3;</code>
     */
    private $valid = false;
    /**
     * Logs that have been generated while processing
     *
     * Generated from protobuf field <code>repeated .handler.LogEntry logs = 4;</code>
     */
    private $logs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $payload
     *           The binary payload
     *     @type string $fields
     *           The decoded fields
     *     @type bool $valid
     *           Was validation of the message successful
     *     @type \Handler\LogEntry[]|\Google\Protobuf\Internal\RepeatedField $logs
     *           Logs that have been generated while processing
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GithubCom\TheThingsNetwork\Api\Handler\Handler::initOnce();
        parent::__construct($data);
    }

    /**
     * The binary payload
     *
     * Generated from protobuf field <code>bytes payload = 1;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * The binary payload
     *
     * Generated from protobuf field <code>bytes payload = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

    /**
     * The decoded fields
     *
     * Generated from protobuf field <code>string fields = 2;</code>
     * @return string
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * The decoded fields
     *
     * Generated from protobuf field <code>string fields = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFields($var)
    {
        GPBUtil::checkString($var, True);
        $this->fields = $var;

        return $this;
    }

    /**
     * Was validation of the message successful
     *
     * Generated from protobuf field <code>bool valid = 3;</code>
     * @return bool
     */
    public function getValid()
    {
        return $this->valid;
    }

    /**
     * Was validation of the message successful
     *
     * Generated from protobuf field <code>bool valid = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setValid($var)
    {
        GPBUtil::checkBool($var);
        $this->valid = $var;

        return $this;
    }

    /**
     * Logs that have been generated while processing
     *
     * Generated from protobuf field <code>repeated .handler.LogEntry logs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogs()
    {
        return $this->logs;
    }

    /**
     * Logs that have been generated while processing
     *
     * Generated from protobuf field <code>repeated .handler.LogEntry logs = 4;</code>
     * @param \Handler\LogEntry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Handler\LogEntry::class);
        $this->logs = $arr;

        return $this;
    }

}

