<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/TheThingsNetwork/api/broker/broker.proto

namespace Broker;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * message StatusRequest is used to request the status of this Broker
 * </pre>
 *
 * Protobuf type <code>broker.StatusRequest</code>
 */
class StatusRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\GithubCom\TheThingsNetwork\Api\Broker\Broker::initOnce();
        parent::__construct();
    }

}

