// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/TheThingsNetwork/api/protocol/lorawan/lorawan.proto

package org.thethingsnetwork.api.protocol.lorawan;

public interface FHDROrBuilder extends
    // @@protoc_insertion_point(interface_extends:lorawan.FHDR)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes dev_addr = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/TheThingsNetwork/ttn/core/types.DevAddr"];</code>
   */
  com.google.protobuf.ByteString getDevAddr();

  /**
   * <code>.lorawan.FCtrl f_ctrl = 2 [(.gogoproto.nullable) = false, (.gogoproto.embed) = true];</code>
   */
  boolean hasFCtrl();
  /**
   * <code>.lorawan.FCtrl f_ctrl = 2 [(.gogoproto.nullable) = false, (.gogoproto.embed) = true];</code>
   */
  org.thethingsnetwork.api.protocol.lorawan.FCtrl getFCtrl();
  /**
   * <code>.lorawan.FCtrl f_ctrl = 2 [(.gogoproto.nullable) = false, (.gogoproto.embed) = true];</code>
   */
  org.thethingsnetwork.api.protocol.lorawan.FCtrlOrBuilder getFCtrlOrBuilder();

  /**
   * <code>uint32 f_cnt = 3;</code>
   */
  int getFCnt();

  /**
   * <code>repeated .lorawan.MACCommand f_opts = 4 [(.gogoproto.nullable) = false];</code>
   */
  java.util.List<org.thethingsnetwork.api.protocol.lorawan.MACCommand> 
      getFOptsList();
  /**
   * <code>repeated .lorawan.MACCommand f_opts = 4 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.protocol.lorawan.MACCommand getFOpts(int index);
  /**
   * <code>repeated .lorawan.MACCommand f_opts = 4 [(.gogoproto.nullable) = false];</code>
   */
  int getFOptsCount();
  /**
   * <code>repeated .lorawan.MACCommand f_opts = 4 [(.gogoproto.nullable) = false];</code>
   */
  java.util.List<? extends org.thethingsnetwork.api.protocol.lorawan.MACCommandOrBuilder> 
      getFOptsOrBuilderList();
  /**
   * <code>repeated .lorawan.MACCommand f_opts = 4 [(.gogoproto.nullable) = false];</code>
   */
  org.thethingsnetwork.api.protocol.lorawan.MACCommandOrBuilder getFOptsOrBuilder(
      int index);
}
