// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/TheThingsNetwork/api/handler/handler.proto

package org.thethingsnetwork.api.handler;

public interface ApplicationIdentifierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:handler.ApplicationIdentifier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string app_id = 1 [(.gogoproto.customname) = "AppID"];</code>
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 1 [(.gogoproto.customname) = "AppID"];</code>
   */
  com.google.protobuf.ByteString
      getAppIdBytes();
}
