/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: github.com/TheThingsNetwork/api/discovery/discovery.proto
 *
 */

/*
 * Copyright 2017, gRPC Authors All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import Foundation
import Dispatch
import gRPC

/// Type for errors thrown from generated client code.
internal enum Discovery_DiscoveryClientError : Error {
  case endOfStream
  case invalidMessageReceived
  case error(c: CallResult)
}

/// Announce (Unary)
internal class Discovery_DiscoveryAnnounceCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/discovery.Discovery/Announce")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Discovery_Announcement,
                       metadata: Metadata) throws -> Google_Protobuf_Empty {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Google_Protobuf_Empty?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Discovery_DiscoveryClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Discovery_Announcement,
                         metadata: Metadata,
                         completion: @escaping (Google_Protobuf_Empty?, CallResult)->())
    throws -> Discovery_DiscoveryAnnounceCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Google_Protobuf_Empty(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// GetAll (Unary)
internal class Discovery_DiscoveryGetAllCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/discovery.Discovery/GetAll")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Discovery_GetServiceRequest,
                       metadata: Metadata) throws -> Discovery_AnnouncementsResponse {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Discovery_AnnouncementsResponse?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Discovery_DiscoveryClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Discovery_GetServiceRequest,
                         metadata: Metadata,
                         completion: @escaping (Discovery_AnnouncementsResponse?, CallResult)->())
    throws -> Discovery_DiscoveryGetAllCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Discovery_AnnouncementsResponse(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// Get (Unary)
internal class Discovery_DiscoveryGetCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/discovery.Discovery/Get")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Discovery_GetRequest,
                       metadata: Metadata) throws -> Discovery_Announcement {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Discovery_Announcement?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Discovery_DiscoveryClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Discovery_GetRequest,
                         metadata: Metadata,
                         completion: @escaping (Discovery_Announcement?, CallResult)->())
    throws -> Discovery_DiscoveryGetCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Discovery_Announcement(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// AddMetadata (Unary)
internal class Discovery_DiscoveryAddMetadataCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/discovery.Discovery/AddMetadata")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Discovery_MetadataRequest,
                       metadata: Metadata) throws -> Google_Protobuf_Empty {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Google_Protobuf_Empty?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Discovery_DiscoveryClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Discovery_MetadataRequest,
                         metadata: Metadata,
                         completion: @escaping (Google_Protobuf_Empty?, CallResult)->())
    throws -> Discovery_DiscoveryAddMetadataCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Google_Protobuf_Empty(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// DeleteMetadata (Unary)
internal class Discovery_DiscoveryDeleteMetadataCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/discovery.Discovery/DeleteMetadata")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Discovery_MetadataRequest,
                       metadata: Metadata) throws -> Google_Protobuf_Empty {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Google_Protobuf_Empty?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Discovery_DiscoveryClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Discovery_MetadataRequest,
                         metadata: Metadata,
                         completion: @escaping (Google_Protobuf_Empty?, CallResult)->())
    throws -> Discovery_DiscoveryDeleteMetadataCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Google_Protobuf_Empty(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// GetByAppID (Unary)
internal class Discovery_DiscoveryGetByAppIDCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/discovery.Discovery/GetByAppID")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Discovery_GetByAppIDRequest,
                       metadata: Metadata) throws -> Discovery_Announcement {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Discovery_Announcement?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Discovery_DiscoveryClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Discovery_GetByAppIDRequest,
                         metadata: Metadata,
                         completion: @escaping (Discovery_Announcement?, CallResult)->())
    throws -> Discovery_DiscoveryGetByAppIDCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Discovery_Announcement(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// GetByGatewayID (Unary)
internal class Discovery_DiscoveryGetByGatewayIDCall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/discovery.Discovery/GetByGatewayID")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Discovery_GetByGatewayIDRequest,
                       metadata: Metadata) throws -> Discovery_Announcement {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Discovery_Announcement?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Discovery_DiscoveryClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Discovery_GetByGatewayIDRequest,
                         metadata: Metadata,
                         completion: @escaping (Discovery_Announcement?, CallResult)->())
    throws -> Discovery_DiscoveryGetByGatewayIDCall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Discovery_Announcement(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// GetByAppEUI (Unary)
internal class Discovery_DiscoveryGetByAppEUICall {
  private var call : Call

  /// Create a call.
  fileprivate init(_ channel: Channel) {
    self.call = channel.makeCall("/discovery.Discovery/GetByAppEUI")
  }

  /// Run the call. Blocks until the reply is received.
  fileprivate func run(request: Discovery_GetByAppEUIRequest,
                       metadata: Metadata) throws -> Discovery_Announcement {
    let sem = DispatchSemaphore(value: 0)
    var returnCallResult : CallResult!
    var returnResponse : Discovery_Announcement?
    _ = try start(request:request, metadata:metadata) {response, callResult in
      returnResponse = response
      returnCallResult = callResult
      sem.signal()
    }
    _ = sem.wait(timeout: DispatchTime.distantFuture)
    if let returnResponse = returnResponse {
      return returnResponse
    } else {
      throw Discovery_DiscoveryClientError.error(c: returnCallResult)
    }
  }

  /// Start the call. Nonblocking.
  fileprivate func start(request: Discovery_GetByAppEUIRequest,
                         metadata: Metadata,
                         completion: @escaping (Discovery_Announcement?, CallResult)->())
    throws -> Discovery_DiscoveryGetByAppEUICall {

      let requestData = try request.serializedData()
      try call.start(.unary,
                     metadata:metadata,
                     message:requestData)
      {(callResult) in
        if let responseData = callResult.resultData,
          let response = try? Discovery_Announcement(serializedData:responseData) {
          completion(response, callResult)
        } else {
          completion(nil, callResult)
        }
      }
      return self
  }
}

/// Call methods of this class to make API calls.
internal class Discovery_DiscoveryService {
  private var channel: Channel

  /// This metadata will be sent with all requests.
  internal var metadata : Metadata

  /// This property allows the service host name to be overridden.
  /// For example, it can be used to make calls to "localhost:8080"
  /// appear to be to "example.com".
  internal var host : String {
    get {
      return self.channel.host
    }
    set {
      self.channel.host = newValue
    }
  }

  /// Create a client that makes insecure connections.
  internal init(address: String) {
    gRPC.initialize()
    channel = Channel(address:address)
    metadata = Metadata()
  }

  /// Create a client that makes secure connections.
  internal init(address: String, certificates: String?, host: String?) {
    gRPC.initialize()
    channel = Channel(address:address, certificates:certificates, host:host)
    metadata = Metadata()
  }

  /// Synchronous. Unary.
  internal func announce(_ request: Discovery_Announcement)
    throws
    -> Google_Protobuf_Empty {
      return try Discovery_DiscoveryAnnounceCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func announce(_ request: Discovery_Announcement,
                  completion: @escaping (Google_Protobuf_Empty?, CallResult)->())
    throws
    -> Discovery_DiscoveryAnnounceCall {
      return try Discovery_DiscoveryAnnounceCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func getall(_ request: Discovery_GetServiceRequest)
    throws
    -> Discovery_AnnouncementsResponse {
      return try Discovery_DiscoveryGetAllCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func getall(_ request: Discovery_GetServiceRequest,
                  completion: @escaping (Discovery_AnnouncementsResponse?, CallResult)->())
    throws
    -> Discovery_DiscoveryGetAllCall {
      return try Discovery_DiscoveryGetAllCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func get(_ request: Discovery_GetRequest)
    throws
    -> Discovery_Announcement {
      return try Discovery_DiscoveryGetCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func get(_ request: Discovery_GetRequest,
                  completion: @escaping (Discovery_Announcement?, CallResult)->())
    throws
    -> Discovery_DiscoveryGetCall {
      return try Discovery_DiscoveryGetCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func addmetadata(_ request: Discovery_MetadataRequest)
    throws
    -> Google_Protobuf_Empty {
      return try Discovery_DiscoveryAddMetadataCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func addmetadata(_ request: Discovery_MetadataRequest,
                  completion: @escaping (Google_Protobuf_Empty?, CallResult)->())
    throws
    -> Discovery_DiscoveryAddMetadataCall {
      return try Discovery_DiscoveryAddMetadataCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func deletemetadata(_ request: Discovery_MetadataRequest)
    throws
    -> Google_Protobuf_Empty {
      return try Discovery_DiscoveryDeleteMetadataCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func deletemetadata(_ request: Discovery_MetadataRequest,
                  completion: @escaping (Google_Protobuf_Empty?, CallResult)->())
    throws
    -> Discovery_DiscoveryDeleteMetadataCall {
      return try Discovery_DiscoveryDeleteMetadataCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func getbyappid(_ request: Discovery_GetByAppIDRequest)
    throws
    -> Discovery_Announcement {
      return try Discovery_DiscoveryGetByAppIDCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func getbyappid(_ request: Discovery_GetByAppIDRequest,
                  completion: @escaping (Discovery_Announcement?, CallResult)->())
    throws
    -> Discovery_DiscoveryGetByAppIDCall {
      return try Discovery_DiscoveryGetByAppIDCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func getbygatewayid(_ request: Discovery_GetByGatewayIDRequest)
    throws
    -> Discovery_Announcement {
      return try Discovery_DiscoveryGetByGatewayIDCall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func getbygatewayid(_ request: Discovery_GetByGatewayIDRequest,
                  completion: @escaping (Discovery_Announcement?, CallResult)->())
    throws
    -> Discovery_DiscoveryGetByGatewayIDCall {
      return try Discovery_DiscoveryGetByGatewayIDCall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
  /// Synchronous. Unary.
  internal func getbyappeui(_ request: Discovery_GetByAppEUIRequest)
    throws
    -> Discovery_Announcement {
      return try Discovery_DiscoveryGetByAppEUICall(channel).run(request:request, metadata:metadata)
  }
  /// Asynchronous. Unary.
  internal func getbyappeui(_ request: Discovery_GetByAppEUIRequest,
                  completion: @escaping (Discovery_Announcement?, CallResult)->())
    throws
    -> Discovery_DiscoveryGetByAppEUICall {
      return try Discovery_DiscoveryGetByAppEUICall(channel).start(request:request,
                                                 metadata:metadata,
                                                 completion:completion)
  }
}

/// Type for errors thrown from generated client code.
internal enum Discovery_DiscoveryManagerClientError : Error {
  case endOfStream
  case invalidMessageReceived
  case error(c: CallResult)
}

/// Call methods of this class to make API calls.
internal class Discovery_DiscoveryManagerService {
  private var channel: Channel

  /// This metadata will be sent with all requests.
  internal var metadata : Metadata

  /// This property allows the service host name to be overridden.
  /// For example, it can be used to make calls to "localhost:8080"
  /// appear to be to "example.com".
  internal var host : String {
    get {
      return self.channel.host
    }
    set {
      self.channel.host = newValue
    }
  }

  /// Create a client that makes insecure connections.
  internal init(address: String) {
    gRPC.initialize()
    channel = Channel(address:address)
    metadata = Metadata()
  }

  /// Create a client that makes secure connections.
  internal init(address: String, certificates: String?, host: String?) {
    gRPC.initialize()
    channel = Channel(address:address, certificates:certificates, host:host)
    metadata = Metadata()
  }

}
