<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/TheThingsNetwork/api/protocol/lorawan/lorawan.proto

namespace Lorawan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>lorawan.DLSettings</code>
 */
class DLSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 rx1_dr_offset = 1;</code>
     */
    private $rx1_dr_offset = 0;
    /**
     * <code>uint32 rx2_dr = 2;</code>
     */
    private $rx2_dr = 0;

    public function __construct() {
        \GPBMetadata\GithubCom\TheThingsNetwork\Api\Protocol\Lorawan\Lorawan::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 rx1_dr_offset = 1;</code>
     */
    public function getRx1DrOffset()
    {
        return $this->rx1_dr_offset;
    }

    /**
     * <code>uint32 rx1_dr_offset = 1;</code>
     */
    public function setRx1DrOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->rx1_dr_offset = $var;
    }

    /**
     * <code>uint32 rx2_dr = 2;</code>
     */
    public function getRx2Dr()
    {
        return $this->rx2_dr;
    }

    /**
     * <code>uint32 rx2_dr = 2;</code>
     */
    public function setRx2Dr($var)
    {
        GPBUtil::checkUint32($var);
        $this->rx2_dr = $var;
    }

}

