<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/TheThingsNetwork/api/protocol/lorawan/lorawan.proto

namespace Lorawan;

/**
 * Protobuf type <code>lorawan.Major</code>
 */
class Major
{
    /**
     * Generated from protobuf enum <code>LORAWAN_R1 = 0;</code>
     */
    const LORAWAN_R1 = 0;
}

