<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/TheThingsNetwork/api/protocol/lorawan/lorawan.proto

namespace Lorawan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lorawan.Metadata</code>
 */
class Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.lorawan.Modulation modulation = 11;</code>
     */
    private $modulation = 0;
    /**
     * LoRa data rate - SF{spreadingfactor}BW{bandwidth}
     *
     * Generated from protobuf field <code>string data_rate = 12;</code>
     */
    private $data_rate = '';
    /**
     * FSK bit rate in bit/s
     *
     * Generated from protobuf field <code>uint32 bit_rate = 13;</code>
     */
    private $bit_rate = 0;
    /**
     * LoRa coding rate
     *
     * Generated from protobuf field <code>string coding_rate = 14;</code>
     */
    private $coding_rate = '';
    /**
     * Store the full 32 bit FCnt (deprecated; do not use)
     *
     * Generated from protobuf field <code>uint32 f_cnt = 15;</code>
     */
    private $f_cnt = 0;
    /**
     * Generated from protobuf field <code>.lorawan.FrequencyPlan frequency_plan = 16;</code>
     */
    private $frequency_plan = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $modulation
     *     @type string $data_rate
     *           LoRa data rate - SF{spreadingfactor}BW{bandwidth}
     *     @type int $bit_rate
     *           FSK bit rate in bit/s
     *     @type string $coding_rate
     *           LoRa coding rate
     *     @type int $f_cnt
     *           Store the full 32 bit FCnt (deprecated; do not use)
     *     @type int $frequency_plan
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GithubCom\TheThingsNetwork\Api\Protocol\Lorawan\Lorawan::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.lorawan.Modulation modulation = 11;</code>
     * @return int
     */
    public function getModulation()
    {
        return $this->modulation;
    }

    /**
     * Generated from protobuf field <code>.lorawan.Modulation modulation = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setModulation($var)
    {
        GPBUtil::checkEnum($var, \Lorawan\Modulation::class);
        $this->modulation = $var;

        return $this;
    }

    /**
     * LoRa data rate - SF{spreadingfactor}BW{bandwidth}
     *
     * Generated from protobuf field <code>string data_rate = 12;</code>
     * @return string
     */
    public function getDataRate()
    {
        return $this->data_rate;
    }

    /**
     * LoRa data rate - SF{spreadingfactor}BW{bandwidth}
     *
     * Generated from protobuf field <code>string data_rate = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDataRate($var)
    {
        GPBUtil::checkString($var, True);
        $this->data_rate = $var;

        return $this;
    }

    /**
     * FSK bit rate in bit/s
     *
     * Generated from protobuf field <code>uint32 bit_rate = 13;</code>
     * @return int
     */
    public function getBitRate()
    {
        return $this->bit_rate;
    }

    /**
     * FSK bit rate in bit/s
     *
     * Generated from protobuf field <code>uint32 bit_rate = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setBitRate($var)
    {
        GPBUtil::checkUint32($var);
        $this->bit_rate = $var;

        return $this;
    }

    /**
     * LoRa coding rate
     *
     * Generated from protobuf field <code>string coding_rate = 14;</code>
     * @return string
     */
    public function getCodingRate()
    {
        return $this->coding_rate;
    }

    /**
     * LoRa coding rate
     *
     * Generated from protobuf field <code>string coding_rate = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setCodingRate($var)
    {
        GPBUtil::checkString($var, True);
        $this->coding_rate = $var;

        return $this;
    }

    /**
     * Store the full 32 bit FCnt (deprecated; do not use)
     *
     * Generated from protobuf field <code>uint32 f_cnt = 15;</code>
     * @return int
     */
    public function getFCnt()
    {
        return $this->f_cnt;
    }

    /**
     * Store the full 32 bit FCnt (deprecated; do not use)
     *
     * Generated from protobuf field <code>uint32 f_cnt = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setFCnt($var)
    {
        GPBUtil::checkUint32($var);
        $this->f_cnt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.lorawan.FrequencyPlan frequency_plan = 16;</code>
     * @return int
     */
    public function getFrequencyPlan()
    {
        return $this->frequency_plan;
    }

    /**
     * Generated from protobuf field <code>.lorawan.FrequencyPlan frequency_plan = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setFrequencyPlan($var)
    {
        GPBUtil::checkEnum($var, \Lorawan\FrequencyPlan::class);
        $this->frequency_plan = $var;

        return $this;
    }

}

