<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/TheThingsNetwork/api/protocol/lorawan/device_address.proto

namespace Lorawan;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lorawan.PrefixesResponse</code>
 */
class PrefixesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The prefixes that are in use or available
     *
     * Generated from protobuf field <code>repeated .lorawan.PrefixesResponse.PrefixMapping prefixes = 1;</code>
     */
    private $prefixes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Lorawan\PrefixesResponse\PrefixMapping[]|\Google\Protobuf\Internal\RepeatedField $prefixes
     *           The prefixes that are in use or available
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GithubCom\TheThingsNetwork\Api\Protocol\Lorawan\DeviceAddress::initOnce();
        parent::__construct($data);
    }

    /**
     * The prefixes that are in use or available
     *
     * Generated from protobuf field <code>repeated .lorawan.PrefixesResponse.PrefixMapping prefixes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrefixes()
    {
        return $this->prefixes;
    }

    /**
     * The prefixes that are in use or available
     *
     * Generated from protobuf field <code>repeated .lorawan.PrefixesResponse.PrefixMapping prefixes = 1;</code>
     * @param \Lorawan\PrefixesResponse\PrefixMapping[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrefixes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Lorawan\PrefixesResponse\PrefixMapping::class);
        $this->prefixes = $arr;

        return $this;
    }

}

